from url_scanner import url_scanner
from img_count_scanner import image_count_scanner
from external_links_scanner import external_links_scanner
from internal_links_scanner import internal_links_scanner
from title_scanner import title_scanner
from cms_scanner import cms_scanner
from description_scanner import description_scanner
from keyword_scanner import keyword_scanner
from alexa_scanners import alexa_rank_scanner, alexa_rank_dk_scanner, alexa_load_time_scanner, alexa_links_ins_scanner, alexa_lang_scanner
from server_scanner import server_scanner
from analytics_scanner import analytics_scanner
from html_scanners import html5_scanner, html5_tag_scanner
